#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'countSwaps' function below.
#
# The function accepts INTEGER_ARRAY a as parameter.
#

def countSwaps(a):
    # Write your code here
        count = 0
        for s in range(0, len(a)):
            for b in range(0, len(a) -1):
                if(a[b]> a[b+1]):
                    # swap(a, a[b], a[b+1])
                    a[b], a[b+1] = a[b+1], a[b]
                    count += 1
        print("Array is sorted in {} swaps.".format(count))
        print(f"First Element: {a[0]}")
        print(f"Last Element: {a[-1]}")

if __name__ == '__main__':
    n = int(input().strip())

    a = list(map(int, input().rstrip().split()))

    countSwaps(a)
